language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7e74bd89-132b-4f71-bc7b-b6a4ae18640f